### ISSUE TITLE
TypeError: id.indexOf is not a function caused while working on development server

### ISSUE THREAD

**Issue by shumiyao** [windicss/gridsome-plugin-windicss#10]
I am using `gridsome-plugin-windicss` version `1.0.2`

I started having an error after starting the gridsome development server.

```
project/node_modules/@windicss/plugin-utils/dist/index.js:601
    if (files.includes(id) || files.includes(id.slice(0, id.indexOf("?"))))
                                                            ^

TypeError: id.indexOf is not a function
    at Object.isDetectTarget (project/node_modules/@windicss/plugin-utils/dist/index.js:601:61)
    at project/node_modules/windicss-webpack-plugin/dist/plugin.js:165:78
    at SyncHook.eval [as call] (eval at create (project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (project/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Watchpack.<anonymous> (project/node_modules/webpack/lib/Watching.js:142:33)
    at Object.onceWrapper (events.js:422:26)
    at Watchpack.emit (events.js:315:20)
    at Watchpack._onChange (project/node_modules/watchpack/lib/watchpack.js:118:7)
    at Watchpack.<anonymous> (project/node_modules/watchpack/lib/watchpack.js:109:8)
    at Watcher.emit (events.js:315:20)
    at DirectoryWatcher.<anonymous> (project/node_modules/watchpack/lib/DirectoryWatcher.js:238:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

The error is caused isDetectTarget function in node_modules/@windicss/plugin-utils/dist/index.js. The error occurs when an id passed to the function is not a string. 

A number looking like a timestamp (just numbers) is passed when the error occurs. Normally ids passed from gridsome to the function is a path. 

Has anyone gotten an issue similar to this?

**Comment by harlan-zw** [comment]
Hey @shumiyao 

Thanks for the issue. Can you try with version `1.0.3` and let me know how it goes.

If there are still issues I'll dig a bit further into it. I haven't been able to replicate this issue before so not exactly sure what your setup is doing.

**Comment by shumiyao** [comment]
Thank you, I will try version 1.0.3

I do not know why but adding the followings to `gridsome.config.js` made the problem go away (with gridsome-plugin-windicss 1.0.2).

```javascript
module.exports = {
...
  configureWebpack: {
    devServer: {
      watchOptions: {
        ignored: "**/.*" // do not know why this is working to prevent webpack / windicss from being crashed.
      }
    }
...
}
```

**Comment by shumiyao** [comment]
I just tried 1.0.3.

The crash is not occurring any more without the workaround above.

Thank you again for your attention. Will post update if I should start seeing the problem.
